### ISSUE TITLE
How to escape dollar signs?

### ISSUE THREAD

**Issue by TripleCamera** [wzpan/hexo-renderer-pandoc#61] opened 2024-01-30 08:28 UTC
How to escape dollar signs if I don't want math formulas?

Source code:
```md
$math$

\$escaped math\$

\\$double escaped math\\$
```

Output: All of them are displayed as math formulas. The third one has a backslash at the beginning.

`_config.yml`:
```yml
pandoc:
  args:
    - "-f"
    - "gfm"
    - "-t"
    - "html"
    - "--mathjax"
```

`_config.next.yml`:
```yml
math:
  mathjax:
    enable: true
```

**Comment by TripleCamera** [comment] 2024-01-30 12:07
None of the following could escape dollar sign, either:
 - `&#36;html escaped math&#36;`
 - `$<!---->comment escaped math<!---->$`
 - `<span>$</span>tag escaped math<span>$</span>`

😞

**Comment by uiolee** [comment] 2024-02-02 05:52
![demo](https://github.com/hexojs/hexo-renderer-pandoc/assets/22849383/1dfb194d-ca45-4ae0-9d29-398409dff89d)


inline backtick code or fenced backtick code



### spec

https://spec.commonmark.org/0.31.2/#code-spans

https://spec.commonmark.org/0.31.2/#fenced-code-blocks

**Comment by uiolee** [comment] 2024-02-02 05:58
can not reproduce.

Backslashes can escape dollar signs. 


------------

![hexo preview](https://github.com/hexojs/hexo-renderer-pandoc/assets/22849383/fc870993-6a09-4634-8200-2dbc90245968 "hexo preview without mathjax")



![image](https://github.com/hexojs/hexo-renderer-pandoc/assets/22849383/a36a56de-32dd-4192-9368-9a43af828b0e "pandoc raw output")

**Comment by TripleCamera** [comment] 2024-02-03 02:31
> can not reproduce.
> 
> Backslashes can escape dollar signs.
> 

Which theme & math engine are you using?

**Comment by TripleCamera** [comment] 2024-02-16 06:55
@uiolee Ping~

**Comment by uiolee** [comment] 2024-02-16 09:31
with `next` theme and `mathjax` enable

![image](https://github.com/hexojs/hexo-renderer-pandoc/assets/22849383/3f3ea44b-069f-44b2-9aca-302cd24403da "hexo preview with next and mathjax")


------------------

`\$sigle escaped math\\$` will works

![image](https://github.com/hexojs/hexo-renderer-pandoc/assets/22849383/d6d02ebc-bce8-436c-b6ef-34abae54cc40 "hexo preview with next and mathjax")

**Comment by uiolee** [comment] 2024-02-16 10:20
`hexo-renderer-pandoc` just simply transpile markdown.In my tests, `hexo-renderer-pandoc` and `hexo` both rendered the correct results

the rendering and displaying formulas is determined by the math engine or theme.
I think this has nothing to do with pandoc or hexo

**Comment by Ritsuka314** [comment] 2024-02-16 18:33
@uiolee you are using pandoc's markdown: `-f markdown` but @TripleCamera want GitHub flavoured markdown: `-f gfm`

@TripleCamera I'm not sure but try this pandoc extension: https://pandoc.org/MANUAL.html#extension-all_symbols_escapable. `pandoc --list-extensions=gfm` tells me this isn't enabled by default.

**Comment by Ritsuka314** [comment] 2024-02-16 18:35
Thanks @uiolee, I've been moving and transferring to a new job so I haven't got time to test this. I wouldn't have thought that `gfm` is the reason.

**Comment by TripleCamera** [comment] 2024-02-17 08:31
All right. I just posted a discussion at next-theme/hexo-theme-next#765.

**Comment by stevenjoezhang** [comment] 2024-05-08 10:49
I think there has been some misunderstanding in this conversation. If users do not want the dollar sign ($) to be interpreted as a mathematical formula, when using `marked`, they can use the following syntax:
```
\\$double escaped math\\$
```

content will be translated by `marked` to
```
\$double escaped math\$
```

and later MathJax will skip rendering. However, when using `pandoc`, it does not preserve the backslash before the dollar sign, and generates
```
$double escaped math$
```

so the formula is always rendered. This is a difference in behavior between `pandoc` and `marked`, and it is unrelated to the theme.

**Closed as completed** 2024-05-08 12:22 UTC
