### ISSUE TITLE
Why it's <embed> instead of <img> tag？

### ISSUE THREAD

**Issue by zhaofei2048** [wzpan/hexo-renderer-pandoc#41] opened 2021-04-06 05:52 UTC
When I insert an image in .md file:
`[alt](http://mydomain.com/img.jpg)`
Then generated HTML will be:
`<embed src="http://mydomain.com/img.jpg">`
Above is not what I want, and I think,it should be: 
`<img src="http://mydomain.com/img.jpg">`
What can I do？Please help me, thankyou！

**Comment by Ritsuka314** [comment] 2021-04-06 07:47
Sorry but I cannot reproduce your problem

I tested on the following `.md` file
```md
[alt](http://mydomain.com/img.jpg)
[alt](http://mydomain.com/img.mp4)

![alt](http://mydomain.com/img.jpg)
![alt](http://mydomain.com/img.mp4)
```
(notice the different syntax for link and media, i think you have a typo in your issue report. Though judged by that you got a `<embed>` tag, you probablly correctly used the second syntax)

I got
```html
<a target="_blank" rel="noopener" href="http://mydomain.com/img.jpg">alt</a>
<a target="_blank" rel="noopener" href="http://mydomain.com/img.mp4">alt</a>

<img src="http://mydomain.com/img.jpg" alt="alt" />
<video src="http://mydomain.com/img.mp4" controls=""><a target="_blank" rel="noopener" href="http://mydomain.com/img.mp4">alt</a></video>
```
as expected.

Actually, when I then went to my older machine with pandoc 2.11.1, for the video I got an image tag. So I suspect that your pandoc is even older than 2.11.1.

Hence, can you 1) report the version of pandoc caused your problem; 2) update pandoc and see if the issue is gone?

**Comment by zhaofei2048** [comment] 2021-04-06 08:20
Thanks for your reply! I am so excited about that you send me a reply.
You reminded me what caused the problem:
Since i am using Aliyun OSS to store my image file, my link accurately is "http://mydomain.com/img.jpg-gz", where "-gz" is a suffix needed by Aliyun OSS if I want to process the image(e.g. add water-mark) before displalying it in the browser.&nbsp;
By the way, my pandoc is on2.2.3.2


谢谢你的回复，通过你的回复。我发现问题出现在哪里了。因为我是使用阿里云对象存储来存储我的图片，而这样图片的src地址后面有一个样式处理后缀-gz，这就使得pandoc不能识别到图片的后缀，从而生成了一个更通用的embed标签。请问有办法可以解决这个问题吗？还是说我必须去掉额外的后缀(这样我就不能使用阿里云对象存储提供的图像处理功能了，例如加水印)
对了，我的博客地址是:feigeek.com
再次感谢您！



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 6, 2021 15:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wzpan/hexo-renderer-pandoc] Why it's <embed&gt; instead of <img&gt; tag？ (#41)




 
Sorry but I cannot reproduce your problem
 
I tested on the following .md file
 [alt](http://mydomain.com/img.jpg) [alt](http://mydomain.com/img.mp4) ![alt](http://mydomain.com/img.jpg) ![alt](http://mydomain.com/img.mp4)
 
(notice the different syntax for link and media, i think you have a typo in your issue report. Though judged by that you got a <embed&gt; tag, you probablly correctly used the second syntax)
 
I got
 <a target="_blank" rel="noopener" href="http://mydomain.com/img.jpg"&gt;alt</a&gt; <a target="_blank" rel="noopener" href="http://mydomain.com/img.mp4"&gt;alt</a&gt; <img src="http://mydomain.com/img.jpg" alt="alt" /&gt; <video src="http://mydomain.com/img.mp4" controls=""&gt;<a target="_blank" rel="noopener" href="http://mydomain.com/img.mp4"&gt;alt</a&gt;</video&gt;
 
as expected.
 
Actually, when I then went to my older machine with pandoc 2.11.1, for the video I got an image tag. So I suspect that your pandoc is even older than 2.11.1.
 
Hence, can you 1) report the version of pandoc caused your problem; 2) update pandoc and see if the issue is gone?

**Comment by Ritsuka314** [comment] 2021-04-06 09:11
Looking at the source code of Pandoc, I see that pandoc inspects the extention of the url and generate HTML tags according to it, and does not give anyway to specify the MIME type. This matter is complicated because Pandoc decided to overload the markdown image syntax for audio/video and other things.

Moreover pandoc filter does not help, since the problem happens after filters are invoked.

So there seem only one way around the problem is this: hardcode the raw HTML tag `<img src="http://mydomain.com/img.jpg-gz" alt="alt" />` in you .md file.

With this markdown
```md
![alt](http://mydomain.com/img.jpg)
![alt](http://mydomain.com/img.mp4)
<img src="http://mydomain.com/img.jpg-gz" alt="alt" />
```
I got
```html
<img src="http://mydomain.com/img.jpg" alt="alt" />
<video src="http://mydomain.com/img.mp4" controls=""><a target="_blank" rel="noopener" href="http://mydomain.com/img.mp4">alt</a></video>
<img src="http://mydomain.com/img.jpg-gz" alt="alt" />
```

**Comment by zhaofei2048** [comment] 2021-04-06 09:27
Thanks a lot! I got.
By the way, the github flavoured task list (or called todo list) cannot be rendered correctly. However, the pandoc support this feature as they stated that in their mannual.



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 6, 2021 17:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wzpan/hexo-renderer-pandoc] Why it's <embed&gt; instead of <img&gt; tag？ (#41)




 
Looking at the source code of Pandoc, I see that pandoc inspects the extention of the url and generate HTML tags according to it, and does not give anyway to specify the MIME type. This matter is complicated because Pandoc decided to overload the markdown image syntax for audio/video and other things.
 
Moreover pandoc filter does not help, since the problem happens after filters are invoked.
 
So there seem only one way around the problem is this: hardcode the raw HTML tag <img src="http://mydomain.com/img.jpg-gz" alt="alt" /&gt; in you .md file.
 
With this markdown
 ![alt](http://mydomain.com/img.jpg) ![alt](http://mydomain.com/img.mp4) <img src="http://mydomain.com/img.jpg-gz" alt="alt" /&gt;
 
I got
 <img src="http://mydomain.com/img.jpg" alt="alt" /&gt; <video src="http://mydomain.com/img.mp4" controls=""&gt;<a target="_blank" rel="noopener" href="http://mydomain.com/img.mp4"&gt;alt</a&gt;</video&gt; <img src="http://mydomain.com/img.jpg-gz" alt="alt" /&gt;

**Comment by Ritsuka314** [comment] 2021-04-06 09:41
Glad I resolved your issue. I'm closing this one now.

As for this:
> the github flavoured task list (or called todo list) cannot be rendered correctly. However, the pandoc support this feature as they stated that in their mannual.

Can you open a new issue and provide a minimal reproducible example there?

**Closed as completed by Ritsuka314** 2021-04-06 09:41 UTC
